-- Migration number: 0002 	 2024-12-27T22:04:18.794Z
ALTER TABLE user ADD COLUMN username TEXT;
ALTER TABLE user ADD COLUMN display_name TEXT;
ALTER TABLE user ADD COLUMN avatar TEXT;
ALTER TABLE user ADD COLUMN links TEXT;
